## Settings
title: huhuzwxy
owner: "zwxy"
url: "https://huhuzwxy.github.io"
baseurl: "/huhuzwxy.github.io"
permalink: /:title/
description: ""
markdown: kramdown
webrick:
  headers:
    Access-Control-Allow-Origin: "*"
## Global Variables
email: "zwxy@mail.ustc.edu.cn"
github: "huhuzwxy/huhuzwxy.github.io"
# path to: css/, fonts/, img/ and js/
assets_path: "/assets" # i.e. "/assets" 
statement: "hhh"
# default max toc levels: 1 - 6 (h1 - h6)
toc_level: 3
# texts randomly displayed in background
bgtext: "αβγδεζηθικλμνξοπρστυφχψω∷∫∮∝∞∧∨∑∏∪∩∈∵∴⊥‖∠⌒⊙≌√"
